server:
  port: 8763
#  context-path: /invoice
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:20001/eureka/,http://localhost:20002/eureka/
      defaultZone: http://localhost:20001/eureka/
spring:
  application:
    name: auth
  
 
    